// Phoneme to Viseme mapping for lip-sync
export const CORRESPONDING_VISEME: Record<string, string> = {
  A: "viseme_aa",
  B: "viseme_PP",
  C: "viseme_I",
  D: "viseme_DD",
  E: "viseme_E",
  F: "viseme_FF",
  G: "viseme_kk",
  H: "viseme_aa",
  I: "viseme_I",
  J: "viseme_CH",
  K: "viseme_kk",
  L: "viseme_nn",
  M: "viseme_PP",
  N: "viseme_nn",
  O: "viseme_O",
  P: "viseme_PP",
  Q: "viseme_kk",
  R: "viseme_RR",
  S: "viseme_SS",
  T: "viseme_DD",
  U: "viseme_U",
  V: "viseme_FF",
  W: "viseme_U",
  X: "viseme_SS",
  Y: "viseme_I",
  Z: "viseme_SS",
  " ": "viseme_sil",
};
